micronaut:
  application:
    name: protobuf

datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true

grpc:
  server:
    health:
      enable: true #default true

##
# Monitoramenteo e metricas
# https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
##
endpoints:
  all:
    port: 8085                      # usa a porta padrão do http-server ou assume a informada
    sensitive: false                # por padrão, a maioria dos endpoints são protegidos por segurança
  health:                           # https://docs.micronaut.io/latest/guide/index.html#healthEndpoint
    enable: true                    # default = true
    sensitive: false                 # default=false
    details-visible: ANONYMOUS  # https://docs.micronaut.io/latest/api/io/micronaut/management/endpoint/health/DetailsVisibility.html